version: "2"

services:
  guildbit:
    build: .
    links:
      - redis
      - murmur-rest
      - db
    environment:
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=8081
      - REDIS_HOST=redis:6379
      - DOCKER_TEST=1
      - C_FORCE_ROOT=true
    ports:
      - "8081:8081"
      - "5555:5555"
    volumes:
      - ".:/opt/guildbit"
      # - "./settings.py:/opt/guildbit/settings.py"
  nginx:
    image: nginx
    volumes:
      - ./etc/nginx/conf.d/guildbit.com:/etc/nginx/conf.d/default.conf
      - ./etc/static:/opt/static
    ports:
      - "8082:80"
    links:
      - guildbit
    environment:
      - NGINX_HOST=guildbit.com
      - NGINX_PORT=80
    command: /bin/bash -c "exec nginx -g 'daemon off;'"

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'guildbit'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  murmur-rest:
    image: alfg/murmur-rest
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8080
      - APP_DEBUG=True
      - ENABLE_AUTH=False
      - USERS=admin:password,admin2:password2
    ports:
      - "8080:8080"
      - "50000-50050:50000-50050"
    volumes:
      - murmurdata:/var/lib/mumble-server/
      # - "./mumble-server/:/var/lib/mumble-server/"

volumes:
  pgdata:
  redisdata:
  murmurdata: